services:
  - type: web
    name: formease-web
    runtime: docker
    plan: free
    region: ohio # Must match DB region!
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://formeasedb_4cnd_user:CtZlySLMspYe0gPa7Lx26l1vnZX7t18O@dpg-d1653g0dl3ps73a0hnf0-a/formeasedb_4cnd
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
