services:
  - type: web
    name: formease-web
    runtime: docker
    env: docker
    plan: free
    region: ohio  # Choose your region
    database:
      name: formease-db
      postgresVersion: 15
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: formease-db
          property: connectionString
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
