services:
  - type: web
    name: formease-web
    runtime: docker
    plan: free
    region: ohio # Must match DB region!
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
         fromDatabase:
          name: FormEaseDb
          property: connectionString
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
