// <auto-generated />
using System;
using FormEase.Infrastructure.PostgreSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormEase.Infrastructure.PostgreSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624062531_SeedTagsTable")]
    partial class SeedTagsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormEase.Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "612e750a-c402-4736-bce4-e6befbb94d0e",
                            Email = "pirmatovalisher2000@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Alisher",
                            IsBlocked = false,
                            LastName = "Pirmatov",
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER2000@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER2000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEjrSDRPQeTFW9w5Z5HqXcwAm530P70tGcs1p57N0avfRoJfsDvoAISpPpRM6fJnJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "098b0e09-5f81-4780-a0cd-0788813e645d",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher2000@gmail.com"
                        },
                        new
                        {
                            Id = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "181df1b7-252c-47fe-830a-d3f83aecaee8",
                            Email = "pirmatovalisher@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            IsBlocked = false,
                            LastName = "Pandya",
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECZ35rQhRQwJDNNPoq2HyP08/8SUdkM81wHuQ2pzkX7V0PToauSB0MmcbnM6Y89l5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b65aac8c-1fd3-4f75-ba48-d594ab03f294",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8570883-8d9e-40b3-8905-f8b6f297283e",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsBlocked = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECv0bZ6f5/jX4QIdrQ2w0r/qSo57WjME8m9h+o25fk+YqdE55d9ooiRdkkqHjBCA4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "26e0ffdf-bc3b-4ab5-b1b5-494c8e53668b",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7fe4b7a-e636-4692-9f1d-2c654f7bd5fb",
                            Email = "creator@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsBlocked = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "CREATOR@EXAMPLE.COM",
                            NormalizedUserName = "CREATOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELrtOgX8U0x1lz7mt7sn2mIFIOg6wTZvAwKmxuuheYFiMBHZbi/JwuKjKCpImKVEPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b6e27f6-e0bb-42e6-9512-9b28675fa524",
                            TwoFactorEnabled = false,
                            UserName = "creator@example.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b3a19d9-9510-48e2-86ee-ee5a96dfc9d3",
                            Email = "respondent@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsBlocked = false,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "RESPONDENT@EXAMPLE.COM",
                            NormalizedUserName = "RESPONDENT@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBOMenXg9ylFqy/TPpEDaKHkC/MDisXdJJMteY1MJIg5YbehMdJaRBmWHZTARzGrtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5d32409-d78e-412d-b965-cca8ce510992",
                            TwoFactorEnabled = false,
                            UserName = "respondent@example.com"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.TemplateTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateTags");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.UserTemplateAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTemplateAccesses");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RespondentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("FormResponses");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInResponseList")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsPublic");

                    b.HasIndex("TopicId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.MetadataModels.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5465),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5472),
                            Name = "Algebra"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5474),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5477),
                            Name = "Workplace"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5479),
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000006"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5483),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000007"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5485),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000008"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5487),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000009"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5489),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000010"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5492),
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000011"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5494),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000012"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5496),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000013"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5497),
                            Name = "AI"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000014"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5511),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000015"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5513),
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000016"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5515),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000017"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5517),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000018"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5520),
                            Name = "Startup"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000019"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5526),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000020"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5528),
                            Name = "E-Learning"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000021"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5530),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000022"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5532),
                            Name = "Geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000023"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5534),
                            Name = "Literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000024"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5535),
                            Name = "Languages"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000025"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5537),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000026"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5539),
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000027"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5541),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000028"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5543),
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000029"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5545),
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000030"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5552),
                            Name = "Mental Health"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000031"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5554),
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000032"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5556),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000033"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5558),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000034"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5561),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000035"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5563),
                            Name = "UX/UI"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000036"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5565),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000037"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5566),
                            Name = "Football"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000038"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5568),
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000039"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5570),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000040"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5572),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000041"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5574),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000042"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5576),
                            Name = "Social Media"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000043"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5578),
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000044"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5580),
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000045"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5581),
                            Name = "Sustainability"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000046"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5583),
                            Name = "Environment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000047"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5585),
                            Name = "Politics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000048"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5587),
                            Name = "Society"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000049"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5589),
                            Name = "Survey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000050"),
                            FirstUsed = new DateTime(2025, 6, 24, 6, 25, 27, 873, DateTimeKind.Utc).AddTicks(5591),
                            Name = "Feedback"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.MetadataModels.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Name = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Name = "Survey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Name = "Feedback"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TemplateId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8815f0d6-db8e-4606-8acb-12844e7b796b",
                            ConcurrencyStamp = "1a0bac98-2b5b-4f6f-8ac1-a78d563a127e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7",
                            ConcurrencyStamp = "59b7449b-4efb-4263-9ad3-f116b5c98277",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            UserId = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000001",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000002",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000003",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.TemplateTag", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.MetadataModels.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("TemplateTags")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.UserTemplateAccess", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("AllowedUsers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "User")
                        .WithMany("AllowedTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Answer", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Respondent")
                        .WithMany("FormResponses")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("FormResponses")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respondent");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.QuestionOption", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Creator")
                        .WithMany("CreatedTemplates")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.MetadataModels.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Comment", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Comments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Like", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Likes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormEase.Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("AllowedTemplates");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTemplates");

                    b.Navigation("FormResponses");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.Navigation("AllowedUsers");

                    b.Navigation("Comments");

                    b.Navigation("FormResponses");

                    b.Navigation("Likes");

                    b.Navigation("Questions");

                    b.Navigation("TemplateTags");
                });
#pragma warning restore 612, 618
        }
    }
}
