// <auto-generated />
using System;
using FormEase.Infrastructure.PostgreSQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace FormEase.Infrastructure.PostgreSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703035452_AddSearchFunctionsAndTriggers")]
    partial class AddSearchFunctionsAndTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormEase.Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "972d0a37-b255-4b53-8a57-c4d709874f62",
                            Email = "pirmatovalisher2000@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Alisher",
                            IsBlocked = false,
                            LastName = "Pirmatov",
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER2000@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER2000@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFWrmScthixoVNBk4IyEJJsOimPJ5bTcw1Ia+fr/yxnYwDOsdvCJwxpypewl0xUmDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a66cd1e4-6531-4b53-b84b-10a049618a12",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher2000@gmail.com"
                        },
                        new
                        {
                            Id = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c382a033-34f7-47b8-a77a-29f8fad16a9a",
                            Email = "pirmatovalisher@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            IsBlocked = false,
                            LastName = "Pandya",
                            LockoutEnabled = false,
                            NormalizedEmail = "PIRMATOVALISHER@GMAIL.COM",
                            NormalizedUserName = "PIRMATOVALISHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIjjvGVoS03Dr826MXXDRDF04NpcMckbhUgUs1+njgvW0eW4ar5K+psIib1Mn7l+7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7baa982-e5c9-4014-9a07-1549e8cef242",
                            TwoFactorEnabled = false,
                            UserName = "pirmatovalisher@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5ad5605-0cfe-4edc-aef9-69f81f586ba2",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsBlocked = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL34DLhVW7BxQQcpJFrj64fPpR/fil8aGqHqQDkAJBJ8DsXQ8FTOMDyPQvbUaXEi1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13fcffb1-4c3f-4c03-8d5a-f266de0de523",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a449fe94-ab93-4714-a7b0-12a8bbbd2ced",
                            Email = "creator@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsBlocked = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "CREATOR@EXAMPLE.COM",
                            NormalizedUserName = "CREATOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH06FGpswU3Ri+9YKJe22Vjj3JpU1th76pLmJpOy3QC91PDezZ1udvFS5Rqq5VHYDA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "690b9225-c2e7-4bfd-843b-2432a598e724",
                            TwoFactorEnabled = false,
                            UserName = "creator@example.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b80c285-ded6-4e28-8836-6648894666cc",
                            Email = "respondent@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            IsBlocked = false,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "RESPONDENT@EXAMPLE.COM",
                            NormalizedUserName = "RESPONDENT@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIrfEh44W5TcLfj/+NKjpcgRBhIF24X+kzQpwIPrHwUiZ7WBWcvG7zrVNgy5kz33MA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e0e252c-1e70-45ad-ac30-4cbfcb058a59",
                            TwoFactorEnabled = false,
                            UserName = "respondent@example.com"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.TemplateTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateTags");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.UserTemplateAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTemplateAccesses");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RespondentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("FormResponses");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInResponseList")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.SelectedOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("OptionId");

                    b.ToTable("SelectedOptions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("TSVECTOR");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsPublic");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TopicId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.MetadataModels.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9910),
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9917),
                            Name = "Algebra"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9920),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9922),
                            Name = "Workplace"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9924),
                            Name = "Science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000006"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9927),
                            Name = "Physics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000007"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9929),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000008"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9931),
                            Name = "Biology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000009"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9933),
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000010"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9937),
                            Name = "Programming"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000011"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9939),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000012"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9941),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000013"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9942),
                            Name = "AI"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000014"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9963),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000015"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9965),
                            Name = "Business"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000016"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9967),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000017"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 161, DateTimeKind.Utc).AddTicks(9968),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000018"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(37),
                            Name = "Startup"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000019"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(40),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000020"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(42),
                            Name = "E-Learning"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000021"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(44),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000022"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(46),
                            Name = "Geography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000023"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(48),
                            Name = "Literature"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000024"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(49),
                            Name = "Languages"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000025"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(51),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000026"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(53),
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000027"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(55),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000028"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(57),
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000029"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(59),
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000030"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(68),
                            Name = "Mental Health"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000031"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(70),
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000032"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(72),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000033"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(73),
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000034"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(77),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000035"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(79),
                            Name = "UX/UI"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000036"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(81),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000037"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(83),
                            Name = "Football"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000038"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(84),
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000039"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(86),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000040"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(88),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000041"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(90),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000042"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(92),
                            Name = "Social Media"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000043"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(94),
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000044"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(96),
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000045"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(98),
                            Name = "Sustainability"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000046"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(100),
                            Name = "Environment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000047"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(102),
                            Name = "Politics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000048"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(104),
                            Name = "Society"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000049"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(106),
                            Name = "Survey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000050"),
                            FirstUsed = new DateTime(2025, 7, 3, 3, 54, 52, 162, DateTimeKind.Utc).AddTicks(108),
                            Name = "Feedback"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.MetadataModels.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Name = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Name = "Survey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Name = "Feedback"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TemplateId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8815f0d6-db8e-4606-8acb-12844e7b796b",
                            ConcurrencyStamp = "8c3d30d0-b428-48af-93a8-954408c98863",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7",
                            ConcurrencyStamp = "d155bb2d-bafc-487d-be76-b95e31c37daf",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Member",
                            UserId = "00000000-0000-0000-0000-000000000003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "bb49ce85-c5c9-41d9-9665-321d430b7e2e",
                            RoleId = "8815f0d6-db8e-4606-8acb-12844e7b796b"
                        },
                        new
                        {
                            UserId = "2ade9cc9-9152-4209-ae22-f2e9e57b09a7",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000001",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000002",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000003",
                            RoleId = "d140eb54-ed6e-4ff2-9199-71fcbe722ef7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.TemplateTag", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.MetadataModels.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("TemplateTags")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.AccessControlModels.UserTemplateAccess", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("AllowedUsers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "User")
                        .WithMany("AllowedTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Answer", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Respondent")
                        .WithMany("FormResponses")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("FormResponses")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respondent");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.QuestionOption", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.SelectedOption", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Answer", "Answer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.QuestionOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Creator")
                        .WithMany("CreatedTemplates")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.MetadataModels.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Comment", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Comments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.PermissionModels.Like", b =>
                {
                    b.HasOne("FormEase.Core.Models.WebApplication.CoreModels.Template", "Template")
                        .WithMany("Likes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FormEase.Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormEase.Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("AllowedTemplates");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTemplates");

                    b.Navigation("FormResponses");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Answer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.FormResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("FormEase.Core.Models.WebApplication.CoreModels.Template", b =>
                {
                    b.Navigation("AllowedUsers");

                    b.Navigation("Comments");

                    b.Navigation("FormResponses");

                    b.Navigation("Likes");

                    b.Navigation("Questions");

                    b.Navigation("TemplateTags");
                });
#pragma warning restore 612, 618
        }
    }
}
